spring:
  profiles:  
    active: prod
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---
# 开发环境配置  
spring:  
  profiles: dev  
server:  
  port: 8080

---
# 测试环境配置  
spring:  
  profiles: test  
server:  
  port: 9090  

---   
# 生产环境配置  
spring:  
  profiles: prod  
server:  
  port: 80 