spring: 
  rabbitmq:
    addresses: 192.168.95.28:5672
    username: admin
    password: passw0rd
    virtual-host: /
    listener:
        type: simple
        direct:
          acknowledge-mode: manual # 开启手动ACK
          prefetch: 200
          retry:
            enabled: true
        simple:
          acknowledge-mode: manual # 开启手动ACK
          prefetch: 200
          retry:
            enabled: true
          default-requeue-rejected: false #true表示会重新放回队列，为false表示不会放回队列