spring:
  datasource:
    druid:
      url: jdbc:mysql://121.43.162.28:3306/sara?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: passw0rd
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always      

mybatis:
  type-aliases-package: com.somnus.springboot.mybatis.model
  mapper-locations: classpath:mapper/*.xml
  
logging:
  level:
    com.somnus.springboot.mybatis.mapper: debug