spring: 
  rabbitmq:
    addresses: 192.168.95.28:5672
    username: admin
    password: passw0rd
    virtual-host: /
    template:
      retry:
        enabled: true
      mandatory: true
    publisher-confirms: true # 开启发送确认
    publisher-returns: true  # 开启发送失败退回
