person:
  lastName: hello
  age: 18
  boss: false
  birth: 2017/12/12
  maps:
    k1: v1
    k2: v2
  maps2: {k1: v1,k2: v2}
  lists:
    - lisi
    - zhaoliu
  lists2: [cat,dog,pig]
  lists3: cat,dog,pig
  dog:
    name: 小狗
    age: 12
  listmap:
    - host: zxj
      port: 10
      active: 9
    - host: ly
      port: 11
      active: 8
  flowers:
    - color: red
      name: rose
    - color: blue
      name: clove