spring:
  redis:
    timeout: 5000
    cluster:
      max-redirects: 5
      nodes:
      - 121.43.162.28:7001
      - 121.43.162.28:7002
      - 47.96.100.166:7001
      - 47.96.100.166:7002
      - 118.24.136.237:7001
      - 118.24.136.237:7002
    database: 0
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 #连接池中的最小空闲连接 默认 0    