spring:
  redis:
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 #连接池中的最小空闲连接 默认 0
    cluster:
      max-redirects: 5
      nodes:
      - 192.168.95.31:6379
      - 192.168.95.32:6379
      - 192.168.95.33:6379
      - 192.168.95.36:6379
      - 192.168.95.37:6379
      - 192.168.95.38:6379
    database: 0
    timeout: 5000
