spring: 
  datasource: 
    url: jdbc:mysql://121.43.162.28:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: passw0rd
    driver-class-name:  com.mysql.jdbc.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always

logging:
  level:
    com.somnus.springboot.mybatis.mapper: debug 