spring:
  #***********************redis***********************
  redis:                  #redis配置
    lettuce:              #lettuce客户端配置
      pool:               #连接池配置
        max-active: 5000  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 1000    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 2000    # 连接池中的最大空闲连接 默认 8
        min-idle: 1000    # 连接池中的最小空闲连接 默认 0
      shutdown-timeout: 100 # 关闭超时时间
    cluster:              #集群配置
      nodes:              #集群节点
        - 192.168.95.31:6379
        - 192.168.95.32:6379
        - 192.168.95.33:6379
        - 192.168.95.36:6379
        - 192.168.95.37:6379
        - 192.168.95.38:6379
      max-redirects: 3    #集群中重定向最大次数
    database: 0
    timeout: 1000         # 连接超时时间（毫秒）