spring:
  redis:
    password: passw0rd
    timeout:  5000
    database: 0 #Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    sentinel:
      nodes:
      - 121.43.162.28:26379
      - 47.96.100.166:26379
      - 118.24.136.237:26379
      master: mymaster
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 8 #连接池中的最大空闲连接 默认 8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 #连接池中的最小空闲连接 默认 0